# This file was generated by GoReleaser. DO NOT EDIT.
cask "rune" do
  desc "Ancient wisdom for modern workflows - A developer-first CLI productivity platform"
  homepage "https://github.com/ferg-cod3s/rune"
  version "0.1.0-alpha.27"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "rune"
  bash_completion "completions/rune.bash"
  zsh_completion "completions/rune.zsh"
  fish_completion "completions/rune.fish"
  depends_on formula: [
      "git",
    ]

  on_macos do
    on_intel do
      url "https://github.com/ferg-cod3s/rune/releases/download/v0.1.0-alpha.27/rune_Darwin_x86_64.tar.gz"
      sha256 "4756c6bcec532aa831a241009f6621f39fde2e39034141db6125015534964044"
    end
    on_arm do
      url "https://github.com/ferg-cod3s/rune/releases/download/v0.1.0-alpha.27/rune_Darwin_arm64.tar.gz"
      sha256 "4966b97096b546abb69e7a20ab4ba6c7a03b0803089fe95ee74827dd9f91b338"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/ferg-cod3s/rune/releases/download/v0.1.0-alpha.27/rune_Linux_x86_64.tar.gz"
      sha256 "3b9864b8c46b3f1a42a02dc9daefbb5c05ba0b9d0890624e4334bd9f1a605828"
    end
    on_arm do
      url "https://github.com/ferg-cod3s/rune/releases/download/v0.1.0-alpha.27/rune_Linux_arm64.tar.gz"
      sha256 "cb524cfcc519841c875286d1c585cd0a9a84eed7c930360bb1985b43399fa4b7"
    end
  end

  postflight do
    # Create default config directory
    system_command "/bin/mkdir", args: ["-p", "#{ENV['HOME']}/.rune"]
  end

  caveats do
    "To get started with rune:"
    "  1. Initialize your configuration: rune init --guided"
    "  2. Start your workday: rune start"
    "  3. Check status: rune status"
    "  4. End your workday: rune stop"
    ""
    "Configuration file location: ~/.rune/config.yaml"
    ""
    "For more information, visit: https://github.com/ferg-cod3s/rune"
  end

  # No zap stanza required
end
