# This file was generated by GoReleaser. DO NOT EDIT.
cask "rune" do
  desc "Ancient wisdom for modern workflows - A developer-first CLI productivity platform"
  homepage "https://github.com/ferg-cod3s/rune"
  version "0.2.0-beta.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "rune"
  bash_completion "completions/rune.bash"
  zsh_completion "completions/rune.zsh"
  fish_completion "completions/rune.fish"
  depends_on formula: [
      "git",
    ]

  on_macos do
    on_intel do
      url "https://github.com/ferg-cod3s/rune/releases/download/v0.2.0-beta.1/rune_Darwin_x86_64.tar.gz"
      sha256 "a17eddb05cdc3985bf3c2d8cc29c4800f3ac6deb7a05f36eb458bd9d0e8783fe"
    end
    on_arm do
      url "https://github.com/ferg-cod3s/rune/releases/download/v0.2.0-beta.1/rune_Darwin_arm64.tar.gz"
      sha256 "639a5ce71515972db5f3632c94292d5f6c9fae075f21963a796b2bd7b11408c1"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/ferg-cod3s/rune/releases/download/v0.2.0-beta.1/rune_Linux_x86_64.tar.gz"
      sha256 "c0049a2cf218c68bb211f04d74d6b06ba82f3096c0498e287441972baf949cc2"
    end
    on_arm do
      url "https://github.com/ferg-cod3s/rune/releases/download/v0.2.0-beta.1/rune_Linux_arm64.tar.gz"
      sha256 "8ffbc046b830698f089ce1d736c284c6b39c79529490d7a4ef72111d7ed12f4c"
    end
  end

  postflight do
    # Create default config directory
    system_command "/bin/mkdir", args: ["-p", "#{ENV['HOME']}/.rune"]
  end

  caveats do
    "To get started with rune:"
    "  1. Initialize your configuration: rune init --guided"
    "  2. Start your workday: rune start"
    "  3. Check status: rune status"
    "  4. End your workday: rune stop"
    ""
    "Configuration file location: ~/.rune/config.yaml"
    ""
    "For more information, visit: https://github.com/ferg-cod3s/rune"
  end

  # No zap stanza required
end
