# This file was generated by GoReleaser. DO NOT EDIT.
cask "rune" do
  desc "Ancient wisdom for modern workflows - A developer-first CLI productivity platform"
  homepage "https://github.com/ferg-cod3s/rune"
  version "0.1.0-alpha.26"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "rune"
  bash_completion "completions/rune.bash"
  zsh_completion "completions/rune.zsh"
  fish_completion "completions/rune.fish"
  depends_on formula: [
      "git",
    ]

  on_macos do
    on_intel do
      url "https://github.com/ferg-cod3s/rune/releases/download/v0.1.0-alpha.26/rune_Darwin_x86_64.tar.gz"
      sha256 "241384af6ead8326bd96a107364c1980ec8f07d82633f8ee22f4792363125e5f"
    end
    on_arm do
      url "https://github.com/ferg-cod3s/rune/releases/download/v0.1.0-alpha.26/rune_Darwin_arm64.tar.gz"
      sha256 "8eac3928957cc5ca0812d2eb91a9d1925b9d5a4c51c836a8862ad9c4220729ef"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/ferg-cod3s/rune/releases/download/v0.1.0-alpha.26/rune_Linux_x86_64.tar.gz"
      sha256 "779a8ec8b28b3cc5d66b52892677478213f7ec22cf890bf84c02a6118d527e84"
    end
    on_arm do
      url "https://github.com/ferg-cod3s/rune/releases/download/v0.1.0-alpha.26/rune_Linux_arm64.tar.gz"
      sha256 "c4e7a9b6cb9a85c85251b9bd682c3950e3dfb9eee8432b2baa842e9b2049048b"
    end
  end

  postflight do
    # Create default config directory
    system_command "/bin/mkdir", args: ["-p", "#{ENV['HOME']}/.rune"]
  end

  caveats do
    "To get started with rune:"
    "  1. Initialize your configuration: rune init --guided"
    "  2. Start your workday: rune start"
    "  3. Check status: rune status"
    "  4. End your workday: rune stop"
    ""
    "Configuration file location: ~/.rune/config.yaml"
    ""
    "For more information, visit: https://github.com/ferg-cod3s/rune"
  end

  # No zap stanza required
end
