# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rune < Formula
  desc "Ancient wisdom for modern workflows - A developer-first CLI productivity platform"
  homepage "https://github.com/ferg-cod3s/rune"
  version "0.1.0-alpha.7"
  license "MIT"

  depends_on "git" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ferg-cod3s/rune/releases/download/v0.1.0-alpha.7/rune_Darwin_x86_64.tar.gz"
      sha256 "b6270b43382269048da29214468c4b6f26b257cb8d3648b40f7aef557be3eaa8"

      def install
        bin.install "rune"

        # Install shell completions
        bash_completion.install "completions/rune.bash" => "rune"
        zsh_completion.install "completions/rune.zsh" => "_rune"
        fish_completion.install "completions/rune.fish"

        # Create default config directory
        (etc/"rune").mkpath
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ferg-cod3s/rune/releases/download/v0.1.0-alpha.7/rune_Darwin_arm64.tar.gz"
      sha256 "d2fb13f33e469ff5d55faafd2793ddf1fae1e86228b141d5c07fcf43bdf5796f"

      def install
        bin.install "rune"

        # Install shell completions
        bash_completion.install "completions/rune.bash" => "rune"
        zsh_completion.install "completions/rune.zsh" => "_rune"
        fish_completion.install "completions/rune.fish"

        # Create default config directory
        (etc/"rune").mkpath
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/ferg-cod3s/rune/releases/download/v0.1.0-alpha.7/rune_Linux_x86_64.tar.gz"
      sha256 "aff9b1c7c56044ea7c25d1d2694de8cf9d91aad18c0b4b1b4b46ea35bc049cb3"
      def install
        bin.install "rune"

        # Install shell completions
        bash_completion.install "completions/rune.bash" => "rune"
        zsh_completion.install "completions/rune.zsh" => "_rune"
        fish_completion.install "completions/rune.fish"

        # Create default config directory
        (etc/"rune").mkpath
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/ferg-cod3s/rune/releases/download/v0.1.0-alpha.7/rune_Linux_arm64.tar.gz"
      sha256 "da798dde02b271e917fb9bc8b72bf38915140bf6a4bf443bbf3adc59e6faebff"
      def install
        bin.install "rune"

        # Install shell completions
        bash_completion.install "completions/rune.bash" => "rune"
        zsh_completion.install "completions/rune.zsh" => "_rune"
        fish_completion.install "completions/rune.fish"

        # Create default config directory
        (etc/"rune").mkpath
      end
    end
  end

  def caveats
    <<~EOS
      To get started with rune:
        1. Initialize your configuration: rune init --guided
        2. Start your workday: rune start
        3. Check status: rune status
        4. End your workday: rune stop

      Configuration file location: ~/.rune/config.yaml

      For more information, visit: https://github.com/ferg-cod3s/rune
    EOS
  end

  test do
    system "#{bin}/rune", "--version"
    system "#{bin}/rune", "--help"
  end
end
