# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Solo < Formula
  desc "Local orchestration layer for coordinating multiple coding agents"
  homepage "https://github.com/v1truv1us/Solo"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/v1truv1us/Solo/releases/download/v0.1.1/Solo_Darwin_x86_64.tar.gz"
      sha256 "bb6f023e787d32c09791424fb41d3914b05a51b63d9300c7d436350ec36c6a86"

      define_method(:install) do
        bin.install "solo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/v1truv1us/Solo/releases/download/v0.1.1/Solo_Darwin_arm64.tar.gz"
      sha256 "73ba2264486789fb6784cc8db462235078713e5270bb6a054eaf3d9295734e35"

      define_method(:install) do
        bin.install "solo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/v1truv1us/Solo/releases/download/v0.1.1/Solo_Linux_x86_64.tar.gz"
      sha256 "d0903805a891b7a6ebc67c1569173829cdfaa58458d1e57e208832f51d2a745c"
      define_method(:install) do
        bin.install "solo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/v1truv1us/Solo/releases/download/v0.1.1/Solo_Linux_arm64.tar.gz"
      sha256 "6664f3df4434986ba5d014a1d11de4466689b317c047012bd35a57db70fbdc89"
      define_method(:install) do
        bin.install "solo"
      end
    end
  end

  def caveats
    <<~EOS
      To get started with Solo:

        1. Initialize a repository:  solo init
        2. Create a task:            solo task create --title "My task" --priority high
        3. Start a session:          solo session start T-1 --worker claude-code
        4. Complete or hand off:     solo session end T-1 --result completed

      For more information, visit: https://github.com/v1truv1us/Solo
    EOS
  end

  test do
    system "#{bin}/solo", "--help"
    system "#{bin}/solo", "health", "--json"
  end
end
