# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Solo < Formula
  desc "Local orchestration layer for coordinating multiple coding agents"
  homepage "https://github.com/v1truv1us/Solo"
  version "0.0.1-alpha"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/v1truv1us/Solo/releases/download/v0.0.1-alpha/Solo_Darwin_x86_64.tar.gz"
      sha256 "24e1d4f8d91e9e535ebdf9085438f41a3edd149de65fb650c5fac9790e00ff13"

      define_method(:install) do
        bin.install "solo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/v1truv1us/Solo/releases/download/v0.0.1-alpha/Solo_Darwin_arm64.tar.gz"
      sha256 "aeb3c212409438454ab32418392faee209555c9a362498d6015f58da29574cf6"

      define_method(:install) do
        bin.install "solo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/v1truv1us/Solo/releases/download/v0.0.1-alpha/Solo_Linux_x86_64.tar.gz"
      sha256 "1ad10b693ad6fb4a56087ff76f1e529bc451cee62819423990a9eae697515ab4"
      define_method(:install) do
        bin.install "solo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/v1truv1us/Solo/releases/download/v0.0.1-alpha/Solo_Linux_arm64.tar.gz"
      sha256 "38f629baac4cc3dd302fd17d242c6bf5f68fbf7f15e465acc551eaee0e093000"
      define_method(:install) do
        bin.install "solo"
      end
    end
  end

  def caveats
    <<~EOS
      To get started with Solo:

        1. Initialize a repository:  solo init
        2. Create a task:            solo task create --title "My task" --priority high
        3. Start a session:          solo session start T-1 --worker claude-code
        4. Complete or hand off:     solo session end T-1 --result completed

      For more information, visit: https://github.com/v1truv1us/Solo
    EOS
  end

  test do
    system "#{bin}/solo", "--help"
    system "#{bin}/solo", "health", "--json"
  end
end
