# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Solo < Formula
  desc "Local orchestration layer for coordinating multiple coding agents"
  homepage "https://github.com/v1truv1us/Solo"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/v1truv1us/Solo/releases/download/v0.1.1/Solo_Darwin_x86_64.tar.gz"
      sha256 "e476c0df832b34e500771519cbe1f6e198f68de8a7d20ea8ea7b8af9e57d73ec"

      define_method(:install) do
        bin.install "solo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/v1truv1us/Solo/releases/download/v0.1.1/Solo_Darwin_arm64.tar.gz"
      sha256 "dfb8d6025d493c028d7b3d589ff2a9c4231745a6d410e94351124a382e37d0f7"

      define_method(:install) do
        bin.install "solo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/v1truv1us/Solo/releases/download/v0.1.1/Solo_Linux_x86_64.tar.gz"
      sha256 "ff3e155993427ab59152de3980d6c6eeb873fe7661adc8ac46604d2a977cccc2"
      define_method(:install) do
        bin.install "solo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/v1truv1us/Solo/releases/download/v0.1.1/Solo_Linux_arm64.tar.gz"
      sha256 "a12b24640eccb14ff2835999321ef2bc2781e8fa94e1c180b740dcbd6d107433"
      define_method(:install) do
        bin.install "solo"
      end
    end
  end

  def caveats
    <<~EOS
      To get started with Solo:

        1. Initialize a repository:  solo init
        2. Create a task:            solo task create --title "My task" --priority high
        3. Start a session:          solo session start T-1 --worker claude-code
        4. Complete or hand off:     solo session end T-1 --result completed

      For more information, visit: https://github.com/v1truv1us/Solo
    EOS
  end

  test do
    system "#{bin}/solo", "--help"
    system "#{bin}/solo", "health", "--json"
  end
end
